import { createFaq, createPage } from "./marketingBase";
import type { MarketingPage } from "./seoTypes";

export const resourcePages: MarketingPage[] = [
  createPage({
    path: "/distribution-flywheel",
    title: "Blog2Video Distribution Flywheel for Medium, Substack, and Video",
    description:
      "A canonical-first distribution workflow that uses your site, Medium, Substack, and video together.",
    eyebrow: "Resource",
    heroTitle: "Run one canonical publishing system across your site, Medium, Substack, and video",
    heroDescription:
      "The strongest SEO and audience strategy is not picking one channel. It is using each channel differently while keeping your site as the canonical home of the content.",
    category: "resource",
    primaryKeyword: "content distribution flywheel",
    keywordVariant: "Medium Substack SEO workflow",
    proofPoints: [
      "Keeps owned-site SEO compounding while still using external platforms for discovery.",
      "Turns each post into a site page, newsletter angle, Medium story, and video asset.",
      "Creates consistent branded search and cross-channel reinforcement over time.",
    ],
    sections: [
      {
        title: "Canonical-first publishing workflow",
        body: [
          "Publish the full, search-targeted version on Blog2Video first. That page becomes the canonical asset that accumulates internal links, schema, and long-term search value.",
          "Then adapt the idea for Substack and Medium instead of posting the exact same piece everywhere. Substack gets commentary and relationship-building. Medium gets narrative thought leadership and distribution hooks.",
        ],
        bullets: [
          "Canonical site post with strong internal links and CTA.",
          "Substack adaptation with extra opinion and an owned-site CTA.",
          "Medium adaptation with a tighter founder-led hook and contextual links.",
          "Video version for YouTube and Shorts that points back to the site page.",
        ],
      },
      {
        title: "Publishing checklist",
        body: [
          "Each topic should produce multiple assets inside the same week so the idea compounds instead of disappearing after one publish.",
        ],
        bullets: [
          "Publish the canonical article on the site.",
          "Adapt it into a Substack issue with a different opening and CTA.",
          "Adapt it into a Medium post with a different framing angle.",
          "Render one long-form explainer and one short-form teaser from the same source.",
        ],
      },
    ],
    recommendedTemplate: "newspaper",
    recommendedTemplateReason:
      "Newspaper works especially well for recurring cross-channel publishing because it gives each piece a serialized editorial feel.",
    faq: createFaq(
      "cross-channel content repurposing",
      "Founders and creators publishing across owned and rented channels",
      "Blog2Video operationalizes a repeatable workflow where each idea becomes multiple assets instead of one-off posts that disappear."
    ),
    relatedPaths: [
      "/for-medium-writers",
      "/for-substack-writers",
      "/blog-to-youtube-video",
      "/blogs/how-to-distribute-one-article-across-blog-newsletter-youtube-and-shorts",
    ],
  }),
  createPage({
    path: "/measurement-playbook",
    title: "SEO Measurement Playbook for Blog2Video",
    description:
      "Track indexation, impressions, CTR, conversions, and channel assists across your SEO program.",
    eyebrow: "Resource",
    heroTitle: "Measure SEO by page type, not just by total traffic",
    heroDescription:
      "The fastest way to learn what is working is to separate commercial pages, blog posts, templates, and programmatic pages so each cluster can improve on its own.",
    category: "resource",
    primaryKeyword: "seo measurement playbook",
    keywordVariant: "search console measurement framework",
    proofPoints: [
      "Makes it easier to see what kind of pages are ranking, converting, and stagnating.",
      "Helps rewrite metadata and internal links based on evidence rather than guesses.",
      "Turns Search Console and Bing data into a weekly operating loop.",
    ],
    sections: [
      {
        title: "Core measurement stack",
        body: [
          "Use Google Search Console and Bing Webmaster Tools to monitor coverage, indexation, and query performance. The sitemap generated by this project should be submitted to both search engines after deployment.",
        ],
        bullets: [
          "Track indexation by page type.",
          "Monitor CTR for pages with high impressions.",
          "Watch assisted signups from Medium and Substack referrals.",
          "Prioritize pages ranking in positions 8 through 20 for optimization.",
        ],
      },
      {
        title: "Weekly reporting cadence",
        body: [
          "Review new indexing issues, pages gaining impressions, and pages that are close to ranking on page one. Then feed those learnings back into metadata, internal links, FAQ depth, and content updates.",
        ],
      },
    ],
    recommendedTemplate: "gridcraft",
    recommendedTemplateReason:
      "Gridcraft is a natural fit for reporting and measurement content because it handles KPI-style communication cleanly.",
    faq: createFaq(
      "SEO measurement",
      "Teams running multiple page types and content channels",
      "Blog2Video's content system gives you enough structure to measure clusters separately instead of treating all organic traffic as one undifferentiated number."
    ),
    relatedPaths: [
      "/distribution-flywheel",
      "/blogs/programmatic-video-generation-for-content-marketers",
      "/blogs/content-repurposing-workflow-for-solo-founders",
      "/pricing",
    ],
  }),
];
