"""Hand-written public API reference, served to paid users by GET /api/api-docs.

Covers every route an API key may call (services/api_route_policy.py) plus the
simplified /api/v1 endpoints. tests/test_api_docs.py fails if an allowed route
has no entry here or an entry names a route that doesn't exist, so edit this
file whenever the policy changes.

Paths are written relative to the host (``/api/...``); the docs page prefixes
the deployment's base URL.
"""
from __future__ import annotations

from typing import Any

JSON = "application/json"
MULTIPART = "multipart/form-data"
FORM = "application/x-www-form-urlencoded"

PROJECT_ID = ("project_id", "path", "integer", True, "Project ID.")
SCENE_ID = ("scene_id", "path", "integer", True, "Scene ID, from the project's `scenes`.")


def _p(name, loc, typ, required, desc):
    return {"name": name, "in": loc, "type": typ, "required": required, "description": desc}


def _f(name, typ, required, desc):
    return {"name": name, "type": typ, "required": required, "description": desc}


def ep(
    method: str,
    path: str,
    summary: str,
    description: str = "",
    *,
    params: list[tuple] | None = None,
    body: list[tuple] | None = None,
    content_type: str = JSON,
    request: Any = None,
    response: Any = None,
    status: int = 200,
    response_note: str | None = None,
    errors: list[str] | None = None,
) -> dict:
    return {
        "method": method,
        "path": path,
        "summary": summary,
        "description": description,
        "params": [_p(*p) for p in (params or [])],
        "body": {"content_type": content_type, "fields": [_f(*f) for f in body]} if body else None,
        "request_example": request,
        "status": status,
        "response_example": response,
        "response_note": response_note,
        "errors": errors or [],
    }


# ─── Shared examples ────────────────────────────────────────────────────────

SCENE = {
    "id": 5012,
    "project_id": 812,
    "order": 1,
    "title": "Why remote teams stall",
    "narration_text": "Most remote teams don't fail on talent. They fail on handoffs.",
    "display_text": "Remote teams fail on handoffs",
    "visual_description": "Split screen of two time zones",
    "remotion_code": "{\"layout\": \"split_stat\", \"layoutProps\": {...}}",
    "preferred_layout": "split_stat",
    "scene_type": "content",
    "voiceover_path": "/media/projects/812/audio/scene_1.mp3",
    "duration_seconds": 7.4,
    "extra_hold_seconds": None,
    "bgm_volume": None,
    "created_at": "2026-09-29T10:14:03",
}

ASSET = {
    "id": 9921,
    "project_id": 812,
    "asset_type": "audio",
    "filename": "scene_1.mp3",
    "r2_url": "https://media.blog2video.app/users/41/projects/812/audio/scene_1.mp3",
    "excluded": False,
    "created_at": "2026-09-29T10:14:09",
    "duration_seconds": None,
    "width": None,
    "height": None,
}

PROJECT = {
    "id": 812,
    "user_id": 41,
    "name": "How remote teams ship faster",
    "blog_url": "https://example.com/remote-teams",
    "status": "generated",
    "template": "default",
    "video_style": "explainer",
    "video_length": "auto",
    "aspect_ratio": "landscape",
    "voice_gender": "female",
    "voice_accent": "american",
    "custom_voice_id": None,
    "content_language": "en",
    "accent_color": "#7C3AED",
    "bg_color": "#FFFFFF",
    "text_color": "#000000",
    "font_family": None,
    "logo_r2_url": None,
    "logo_position": "bottom_right",
    "playback_speed": 1.0,
    "bgm_track_id": "corporate_upbeat",
    "bgm_volume": 0.1,
    "captions_enabled": True,
    "caption_position": "bottom_center",
    "stock_footage_enabled": False,
    "r2_video_url": None,
    "created_at": "2026-09-29T10:12:40",
    "updated_at": "2026-09-29T10:15:02",
    "scenes": [SCENE],
    "assets": [ASSET],
}

VOICE_JOB_STATUS = {
    "active": True,
    "done": False,
    "error": None,
    "total": 6,
    "completed": 2,
    "progress": 33,
    "status": "voice_regenerating",
    "r2_video_url": None,
    "kind": "voice_change",
}

SAVED_VOICE = {
    "id": 17,
    "voice_id": "21m00Tcm4TlvDq8ikWAM",
    "name": "Rachel",
    "preview_url": "https://.../rachel.mp3",
    "source": "prebuilt",
    "plan": "free",
    "gender": "female",
    "accent": "american",
    "description": "Calm, clear narrator",
    "created_at": "2026-09-01T08:00:00",
    "custom_voice_id": None,
}

CUSTOM_VOICE = {
    "id": 4,
    "name": "My narrator",
    "voice_id": "pNInz6obpgDQGcFmaJgB",
    "source": "clone",
    "prompt_text": None,
    "form_gender": None,
    "form_age": None,
    "form_persona": None,
    "form_speed": None,
    "form_accent": None,
    "preview_url": "https://.../preview.mp3",
    "created_at": "2026-09-20T12:00:00",
}

CUSTOM_TEMPLATE_ID = ("template_id", "path", "integer", True, "Numeric template ID. Use `custom_<id>` only as a project's `template` value.")

CUSTOM_TEMPLATE = {
    "id": 58,
    "name": "Acme brand",
    "source_url": "https://acme.com",
    "category": "blog",
    "theme": {"colors": {"accent": "#FF5A1F", "bg": "#0B0B0F", "text": "#FFFFFF"}, "fonts": {"heading": "Inter"}},
    "preview_colors": {"accent": "#FF5A1F", "bg": "#0B0B0F", "text": "#FFFFFF"},
    "intro_code": "...",
    "outro_code": "...",
    "content_codes": ["..."],
    "preview_image_url": "https://.../custom_58.png",
}

# ─── Guides ─────────────────────────────────────────────────────────────────

GUIDES = [
    {
        "id": "authentication",
        "title": "Authentication",
        "blocks": [
            {"type": "p", "text": "Send your API key in the `Authorization` header of every request. Create a key on the API Keys page, and keep it on your server."},
            {"type": "code", "text": "Authorization: Bearer b2v_live_xxxxxxxxxxxxxxxxxxxxxxxx"},
            {"type": "p", "text": "Videos you create use your account's plan. The API needs a paid plan."},
        ],
    },
    {
        "id": "quick-flow",
        "title": "Quick start",
        "blocks": [
            {"type": "p", "text": "1. Create a video. Send a `url`, or your own text as `content` (50+ characters) with a `title`. Generation starts right away and uses one video from your plan."},
            {"type": "code", "text": "curl -X POST $B2V/api/v1/videos \\\n  -H \"Authorization: Bearer $KEY\" \\\n  -H \"Content-Type: application/json\" \\\n  -H \"Idempotency-Key: post-123\" \\\n  -d '{\"url\": \"https://example.com/remote-teams\"}'\n\n# 202 → {\"video_id\": 812, \"state\": \"queued\"}"},
            {"type": "table", "columns": ["Option", "Values"], "rows": [
                ["`template`", "`default` (built-in ids from `GET /api/v1/catalog`), `custom_<id>` or a crafted template id."],
                ["`video_style`", "`auto`, `explainer`, `promotional`, `storytelling` or a custom style."],
                ["`video_length`", "`auto`, `short`, `medium`, `detailed` or `more_detailed`."],
                ["`aspect_ratio`", "`landscape` or `portrait`."],
                ["`voice_gender` / `voice_accent`", "`female`, `male` or `none` / `american` or `british`. `custom_voice_id` overrides both."],
                ["`content_language`", "e.g. `es` or `Spanish`."],
                ["`captions_enabled` / `stock_footage_enabled`", "`true` or `false`."],
                ["`external_user_id` / `metadata`", "Your own user id and any JSON (up to 4 KB), returned with the video."],
            ]},
            {"type": "p", "text": "Colors, fonts, music, captions, logo and avatar settings use the same names as in Update video settings. The `Idempotency-Key` header is optional: resending the same key returns the first video instead of creating another."},
            {"type": "p", "text": "2. Wait for it. Poll every few seconds until `ready` is true (or `status` is `error`)."},
            {"type": "code", "text": "curl $B2V/api/v1/videos/812/status -H \"Authorization: Bearer $KEY\"\n\n# {\"video_id\": 812, \"status\": \"generated\", \"ready\": true, \"error\": null, \"video_url\": null}"},
            {"type": "p", "text": "3. Get the video. Returns the scenes with their voiceover URLs, a `preview_url` that plays the video without rendering, and `embed_html` to put that player on a page."},
            {"type": "code", "text": "curl $B2V/api/v1/videos/812 -H \"Authorization: Bearer $KEY\""},
            {"type": "p", "text": "4. Render the MP4 (optional). Start the render, then poll the same path until `done` is true. `r2_video_url` is the file."},
            {"type": "code", "text": "curl -X POST \"$B2V/api/v1/videos/812/render?resolution=1080p\" -H \"Authorization: Bearer $KEY\"\ncurl $B2V/api/v1/videos/812/render -H \"Authorization: Bearer $KEY\"\n\n# {\"progress\": 100, \"done\": true, \"r2_video_url\": \"https://media.blog2video.app/…/video.mp4\"}"},
        ],
    },
    {
        "id": "errors",
        "title": "Errors",
        "blocks": [
            {"type": "p", "text": "Errors return JSON with a `detail` field: a message, or an object with an `error` code."},
            {"type": "table", "columns": ["Status", "Meaning"], "rows": [
                ["400", "The request is not valid in the project's current state."],
                ["401", "The API key is missing, invalid, revoked or rotated."],
                ["402", "The video quota for the billing period is exhausted (`quota_exceeded`)."],
                ["403", "The plan, endpoint or available credits do not permit the request."],
                ["404", "The resource does not exist or belongs to another account."],
                ["409", "A job is already running for this resource."],
                ["422", "Validation failed; `detail` lists the invalid fields."],
                ["429", "Rate limit exceeded; retry after the `Retry-After` interval."],
            ]},
            {"type": "code", "text": "{\n  \"detail\": {\n    \"error\": \"endpoint_not_available_with_api_key\",\n    \"message\": \"This endpoint can't be called with an API key.\"\n  }\n}"},
        ],
    },
    {
        "id": "limits",
        "title": "Usage and background jobs",
        "blocks": [
            {"type": "p", "text": "Each new project uses one video from the plan. AI features (image generation, AI edits and avatars) use AI-edit credits. `GET /api/auth/me` reports remaining usage."},
            {"type": "p", "text": "Long-running operations run in the background and return immediately. Poll the matching status endpoint no more than once every 2 seconds."},
        ],
    },
    {
        "id": "custom-template-flow",
        "title": "Custom templates",
        "blocks": [
            {"type": "list", "items": [
                "`POST /api/custom-templates/extract-theme`: extract a theme from a URL (or use `extract-theme-from-doc` or `extract-theme-from-prompt`).",
                "`POST /api/custom-templates`: create the template from the theme.",
                "`POST /api/custom-templates/{template_id}/generate-code`: generate the scenes; poll `generation-status` until `complete`.",
                "Create a video with `template: \"custom_<id>\"`.",
            ]},
            {"type": "p", "text": "AI scene edits are saved as drafts. Applying a draft saves a version that can be restored."},
        ],
    },
    {
        "id": "your-app",
        "title": "Serving your own users",
        "blocks": [
            {"type": "p", "text": "An application may serve its own users with a single key. All usage is billed to the key owner's account."},
            {"type": "list", "items": [
                "Call the API from your backend only.",
                "Tag videos with `external_user_id`; filter with `GET /api/v1/videos?external_user_id=…`.",
                "Verify ownership before returning a video to a user. The key can access every video it created.",
                "Prefix `Idempotency-Key` values with the user's id. Keys are unique per account.",
                "Monitor `videos_remaining` with `GET /api/v1/me`.",
            ]},
        ],
    },
]

# ─── Sections ───────────────────────────────────────────────────────────────

SECTIONS = [
    {
        "id": "account",
        "title": "Account",
        "description": "The key owner's plan and remaining usage.",
        "endpoints": [
            ep("GET", "/api/auth/me", "Get account",
               "Returns the plan, video usage and AI-edit credits.",
               response={
                   "id": 41, "email": "you@company.com", "name": "Sam", "plan": "pro",
                   "videos_used_this_period": 12, "video_limit": 100, "can_create_video": True,
                   "ai_edit_credits": 40, "ai_edit_allowance_remaining": 4870,
                   "custom_templates_created": 3, "custom_template_limit": 20, "can_create_custom_template": True,
               }),
        ],
    },
    {
        "id": "projects",
        "title": "Projects",
        "description": "Create and manage video projects. Each new project uses one video.",
        "endpoints": [
            ep("POST", "/api/projects/upload", "Create a project from documents",
               "Creates a project from up to 5 files (PDF, DOCX, PPTX, TXT, MD). Accepts the URL-creation options as form fields.",
               content_type=MULTIPART,
               body=[
                   ("files", "file[]", True, "One or more documents."),
                   ("name", "string", False, "Project name."),
                   ("template / video_style / video_length / aspect_ratio / voice_gender / voice_accent / content_language …", "string", False, "Same meaning as in `POST /api/v1/videos`."),
               ],
               request="curl -X POST $B2V/api/projects/upload -H \"Authorization: Bearer $KEY\" -F files=@report.pdf -F template=default",
               response={**PROJECT, "blog_url": None, "status": "created", "scenes": []}),
            ep("GET", "/api/projects", "List projects",
               "Newest first. Returns an array, or a paginated object when `page` is set.",
               params=[
                   ("page", "query", "integer", False, "Page number (1-based). Enables pagination."),
                   ("per_page", "query", "integer", False, "Page size. Default 10."),
               ],
               response=[{"id": 812, "name": "How remote teams ship faster", "blog_url": "https://example.com/remote-teams", "status": "done", "created_at": "2026-09-29T10:12:40", "updated_at": "2026-09-29T10:40:11", "scene_count": 8, "role": "owner"}],
               response_note="With `page`: `{ \"items\": [...], \"total\": 37, \"page\": 1, \"per_page\": 10 }`."),
            ep("GET", "/api/projects/{project_id}", "Get a project",
               "Returns settings, ordered `scenes` and `assets`. Voiceovers are `audio` assets matched to scenes by `voiceover_path`.",
               params=[PROJECT_ID], response=PROJECT),
            ep("PATCH", "/api/projects/{project_id}/update-project", "Update project settings",
               "Updates visual settings. Send only the fields to change.",
               params=[PROJECT_ID],
               body=[
                   ("accent_color / bg_color / text_color", "string", False, "Hex colors."),
                   ("font_family", "string", False, "Font id."),
                   ("aspect_ratio", "string", False, "`landscape` or `portrait`."),
                   ("playback_speed", "number", False, "0.5 to 2.5."),
                   ("bgm_track_id / bgm_volume", "string / number", False, "Background music; send `bgm_track_id: null` to remove."),
                   ("captions_enabled / caption_position / caption_font_family / caption_font_size / caption_offset", "mixed", False, "Caption settings; position is `bottom_center` or `top_center`, offset -100 to 100."),
                   ("video_length / content_language", "string", False, "Used by later regenerations."),
                   ("avatar_shape / avatar_size / avatar_position / avatar_bg / avatar_opacity / avatar_shadow / avatar_motion_style", "mixed", False, "Presenter overlay appearance."),
               ],
               request={"accent_color": "#0EA5E9", "captions_enabled": True, "playback_speed": 1.1},
               response=PROJECT),
            ep("PATCH", "/api/projects/{project_id}", "Update logo placement",
               params=[PROJECT_ID],
               body=[
                   ("logo_position", "string", False, "`top_left`, `top_right`, `bottom_left` or `bottom_right`."),
                   ("logo_size", "number", False, "Percent of the default size."),
                   ("logo_opacity", "number", False, "0 to 1."),
               ],
               request={"logo_position": "top_right", "logo_opacity": 0.8},
               response=PROJECT),
            ep("POST", "/api/projects/{project_id}/logo", "Upload a logo",
               "PNG, JPG, SVG or WebP. Shown on every scene.",
               params=[PROJECT_ID], content_type=MULTIPART, body=[("file", "file", True, "The logo image.")],
               response={"logo_url": "https://media.blog2video.app/.../logo.png", "logo_position": "bottom_right"}),
            ep("DELETE", "/api/projects/{project_id}/logo", "Remove the logo", params=[PROJECT_ID], response={"detail": "Logo removed"}),
            ep("POST", "/api/projects/{project_id}/upload-documents", "Add source documents",
               "Adds documents before generation.",
               params=[PROJECT_ID], content_type=MULTIPART, body=[("files", "file[]", True, "Documents to add.")],
               response=PROJECT),
            ep("DELETE", "/api/projects/{project_id}", "Delete a project",
               "Permanently deletes the project and its media.",
               params=[PROJECT_ID], response={"detail": "Project deleted"}),
            ep("GET", "/api/projects/template-availability", "Check template availability",
               "Indicates whether the account has custom or crafted templates.",
               response={"has_custom_templates": True, "has_crafted_templates": False}),
            ep("GET", "/api/projects/{project_id}/layouts", "List template layouts",
               "Layouts supported by the project's template, for use as `layout` in scene regeneration.",
               params=[PROJECT_ID],
               response={"layouts": ["bullet_list", "hero_image", "hero_image--left", "quote", "split_stat"], "selectable_layouts": ["bullet_list", "hero_image", "quote", "split_stat"], "layout_names": {"hero_image--left": "Hero Image — Left"}, "layouts_without_image": ["bullet_list", "quote"], "layout_variants": {"hero_image": ["hero_image--left"]}},
               response_note="Includes `layout_prop_schema`, `content_prop_schema` and `layout_content_types`."),
            ep("PATCH", "/api/projects/{project_id}/assets/{asset_id}/exclude", "Include or exclude an image",
               "Includes or excludes a scraped image from scenes.",
               params=[PROJECT_ID, ("asset_id", "path", "integer", True, "The asset's id.")],
               response={"id": 9930, "excluded": True}),
            ep("DELETE", "/api/projects/{project_id}/assets/{asset_id}", "Delete an asset",
               params=[PROJECT_ID, ("asset_id", "path", "integer", True, "The asset's id.")],
               response={"detail": "Asset deleted"}),
        ],
    },
    {
        "id": "generation",
        "title": "Generation & status",
        "description": "Generate scenes and voiceovers, and track progress.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/generate", "Start generation",
               "Runs the full pipeline in the background and returns immediately.",
               params=[PROJECT_ID],
               response={"detail": "Pipeline started", "step": 0},
               response_note="`detail` reports `Already generated`, `Pipeline already running`, `Awaiting script review` or `Awaiting stock footage review` when applicable."),
            ep("GET", "/api/projects/{project_id}/status", "Get generation status",
               "Poll every 3–5 seconds. Complete when `running` is false and `status` is `generated`.",
               params=[PROJECT_ID],
               response={"status": "scripted", "step": 3, "running": True, "error": None, "error_code": None, "notice": None, "stock_footage": None, "project_removed": False},
               response_note="`status`: `created`, `scraped`, `scripted`, `awaiting_script_review`, `generated`, `awaiting_stock_footage_review`, `rendering`, `done`, `error`. A failed project may be removed and refunded (`project_removed: true`)."),
            ep("POST", "/api/projects/{project_id}/scrape", "Run the scrape step",
               "Runs only the source-reading step. Use `generate` for the full pipeline.",
               params=[PROJECT_ID], response={**PROJECT, "status": "scraped", "scenes": []}),
            ep("POST", "/api/projects/{project_id}/generate-script", "Run the script step",
               params=[PROJECT_ID], response={**PROJECT, "status": "scripted", "scenes": []}),
            ep("POST", "/api/projects/{project_id}/generate-scenes", "Run the scene step",
               params=[PROJECT_ID], response=PROJECT),
            ep("POST", "/api/projects/{project_id}/script-review/approve", "Approve the script",
               "For projects with `script_review_enabled`. Submits the scenes and resumes generation.",
               params=[PROJECT_ID],
               body=[("scenes", "array", True, "Each item: `id`, `title`, `narration_text`, `display_text`, optional `preferred_layout`.")],
               request={"scenes": [{"id": 5012, "title": "Why remote teams stall", "narration_text": "Most remote teams…", "display_text": "Remote teams fail on handoffs"}]},
               response={"project": PROJECT, "preference_learning": None}),
            ep("POST", "/api/projects/{project_id}/script-review/scenes/{scene_id}/narration-preview", "Preview scene narration",
               "Rewrites one scene's narration to match edited on-screen text.",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("title", "string", True, "Scene title."),
                   ("display_text", "string", True, "On-screen text."),
                   ("narration_text", "string", False, "Current narration."),
                   ("draft_scenes", "array", True, "All scenes in their current draft form (`id`, `title`, `display_text`, `narration_text`)."),
                   ("revision", "integer", True, "Client revision counter; returned unchanged."),
               ],
               response={"revision": 3, "title": "Why remote teams stall", "display_text": "…", "narration_text": "…", "source_fingerprint": "a1b2c3"}),
            ep("POST", "/api/projects/{project_id}/regenerate-script", "Regenerate the script",
               "Rewrites titles, on-screen text and layouts; keeps narration and voiceovers. Runs in the background.",
               params=[PROJECT_ID],
               body=[("user_instruction", "string", False, "Optional guidance, e.g. \"shorter titles, more numbers\".")],
               response={"id": 77, "project_id": 812, "status": "queued", "current_step": "queued", "total_scenes": 8, "processed_scenes": 0, "error_message": None, "user_instruction": "shorter titles"}),
            ep("GET", "/api/projects/{project_id}/regenerate-script-status", "Get script regeneration status",
               params=[PROJECT_ID],
               response={"id": 77, "project_id": 812, "status": "awaiting_verification", "current_step": "done", "total_scenes": 8, "processed_scenes": 8, "error_message": None},
               response_note="`null` if no job has run. At `awaiting_verification`, call `verify` to keep the result or `regenerate` to retry."),
            ep("GET", "/api/projects/{project_id}/regenerate-script/preview", "Get previous scenes",
               "Returns the scenes from before regeneration, for comparison.",
               params=[PROJECT_ID],
               response={"previous_scenes": [{"order": 1, "title": "Old title", "display_text": "…", "narration_text": "…", "visual_description": "…", "preferred_layout": "bullet_list"}]}),
            ep("POST", "/api/projects/{project_id}/regenerate-script/verify", "Accept the regenerated script",
               params=[PROJECT_ID], response={"id": 77, "status": "completed"}),
            ep("POST", "/api/projects/{project_id}/regenerate-script/regenerate", "Retry script regeneration",
               params=[PROJECT_ID],
               body=[("user_instruction", "string", False, "New guidance for the retry.")],
               response={"id": 78, "status": "queued"}),
        ],
    },
    {
        "id": "scenes",
        "title": "Scenes",
        "description": "Edit, add, reorder, regenerate and delete scenes.",
        "endpoints": [
            ep("PUT", "/api/projects/{project_id}/scenes/{scene_id}", "Edit a scene",
               "Send only the fields to change. Changing `narration_text` does not re-record the voiceover.",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("title", "string", False, "Scene title."),
                   ("display_text", "string", False, "On-screen text."),
                   ("narration_text", "string", False, "Narration script."),
                   ("visual_description", "string", False, "Description used to pick or generate visuals."),
                   ("duration_seconds", "number", False, "Scene length in seconds."),
                   ("extra_hold_seconds", "number", False, "Extra time to hold the last frame."),
                   ("bgm_volume", "number", False, "Per-scene music volume 0 to 1."),
                   ("remotion_code", "string", False, "Advanced: the scene's layout descriptor JSON."),
               ],
               request={"title": "Handoffs, not talent", "display_text": "Teams fail on handoffs"},
               response={**SCENE, "title": "Handoffs, not talent", "display_text": "Teams fail on handoffs"}),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/regenerate", "Regenerate a scene",
               "Rebuilds one scene, optionally with new narration and voiceover. Uses AI-edit credits.",
               params=[PROJECT_ID, SCENE_ID], content_type=MULTIPART,
               body=[
                   ("description", "string", False, "What the scene should show or say."),
                   ("narration_text", "string", False, "New narration."),
                   ("regenerate_voiceover", "string", False, "`true` to re-record the voiceover. Default `false`."),
                   ("voiceover_verbatim", "string", False, "`true` reads `narration_text` exactly; `false` allows AI refinement. Default `true`."),
                   ("layout", "string", False, "Force a layout from `GET /api/projects/{project_id}/layouts`."),
                   ("image", "file", False, "Image to use in the scene."),
               ],
               request="curl -X POST $B2V/api/projects/812/scenes/5012/regenerate -H \"Authorization: Bearer $KEY\" -F description=\"Show the 3 biggest handoff delays as a chart\" -F regenerate_voiceover=true",
               response=SCENE,
               errors=["403: insufficient AI-edit credits."]),
            ep("POST", "/api/projects/{project_id}/scenes/add", "Add a scene",
               "Generates and inserts a scene from a prompt. Runs in the background; poll `add-status`.",
               params=[PROJECT_ID],
               body=[
                   ("prompt", "string", True, "What the new scene should cover."),
                   ("position", "integer", False, "1-based position to insert at. Appends when omitted."),
               ],
               request={"prompt": "A closing tip about async standups", "position": 6},
               response={"id": 31, "status": "queued", "current_step": "queued", "error_message": None, "new_scene_id": None, "position": 6}),
            ep("GET", "/api/projects/{project_id}/scenes/add-status", "Get add-scene status",
               params=[PROJECT_ID],
               response={"id": 31, "status": "completed", "current_step": "done", "error_message": None, "new_scene_id": 5020, "position": 6},
               response_note="`status`: `queued`, `running`, `completed` or `failed`. `null` when no job has run."),
            ep("POST", "/api/projects/{project_id}/scenes/reorder", "Reorder scenes",
               params=[PROJECT_ID],
               body=[("scene_orders", "array", True, "Every scene's `scene_id` with its new 1-based `order`.")],
               request={"scene_orders": [{"scene_id": 5013, "order": 1}, {"scene_id": 5012, "order": 2}]},
               response=[{**SCENE, "id": 5013, "order": 1}, {**SCENE, "order": 2}]),
            ep("PUT", "/api/projects/{project_id}/bulk-update-scenes", "Set font sizes for all scenes",
               params=[PROJECT_ID],
               body=[
                   ("title_font_size", "integer", False, "Title size in px."),
                   ("description_font_size", "integer", False, "Body text size in px."),
               ],
               request={"title_font_size": 64},
               response=[SCENE]),
            ep("DELETE", "/api/projects/{project_id}/scenes/{scene_id}", "Delete a scene",
               params=[PROJECT_ID, SCENE_ID], status=204, response=None,
               response_note="No content."),
        ],
    },
    {
        "id": "images",
        "title": "Images & stock footage",
        "description": "Manage scene images and stock footage.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/image", "Upload a scene image",
               params=[PROJECT_ID, SCENE_ID], content_type=MULTIPART,
               body=[("image", "file", True, "PNG, JPG or WebP.")],
               response=SCENE),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/generate-image", "Generate an AI image",
               "Returns an image to upload with the scene image endpoint. Uses AI-edit credits; failures are not charged.",
               params=[PROJECT_ID, SCENE_ID],
               body=[("image_description", "string", True, "What the image should show.")],
               request={"image_description": "A calm home office at sunrise, flat illustration"},
               response={"image_base64": "iVBORw0KGgoAAAANSUhEUg…", "refined_prompt": "Flat illustration of a calm home office at sunrise…"}),
            ep("PATCH", "/api/projects/{project_id}/scenes/{scene_id}/image-focus", "Set image framing",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("image_focus_x / image_focus_y", "number", False, "Focal point in percent (0 to 100). Default 50/50."),
                   ("image_zoom", "number", False, "Zoom factor."),
                   ("video_start_seconds", "number", False, "For stock clips: where playback starts."),
               ],
               request={"image_focus_x": 30, "image_focus_y": 45, "image_zoom": 1.2},
               response=SCENE),
            ep("POST", "/api/projects/{project_id}/images/move", "Move an image between scenes",
               params=[PROJECT_ID],
               body=[("from_scene_id", "integer", True, "Scene that has the image."), ("to_scene_id", "integer", True, "Scene that receives it.")],
               response={"detail": "Image moved"}),
            ep("POST", "/api/projects/{project_id}/images/swap", "Swap two scenes' images",
               params=[PROJECT_ID],
               body=[("first_scene_id", "integer", True, "First scene."), ("second_scene_id", "integer", True, "Second scene.")],
               response={"detail": "Images swapped"}),
            ep("POST", "/api/projects/{project_id}/images/duplicate", "Copy an image to another scene",
               params=[PROJECT_ID],
               body=[("source_scene_id", "integer", True, "Scene to copy from."), ("target_scene_id", "integer", True, "Scene to copy to.")],
               response={"detail": "Image duplicated to target scene"}),
            ep("POST", "/api/projects/{project_id}/images/assign-existing", "Assign a project image to a scene",
               params=[PROJECT_ID],
               body=[("scene_id", "integer", True, "Target scene."), ("asset_id", "integer", True, "An `image` asset of this project.")],
               response={"detail": "Image assigned to scene"}),
            ep("GET", "/api/projects/{project_id}/stock-footage/search", "Search stock footage",
               "Searches Pexels and Pixabay. No charge.",
               params=[
                   PROJECT_ID,
                   ("q", "query", "string", True, "Search terms."),
                   ("provider", "query", "string", False, "`all`, `pexels` or `pixabay`. Default `all`."),
                   ("page", "query", "integer", False, "Default 1."),
                   ("per_page", "query", "integer", False, "Default 6."),
                   ("box_w / box_h", "query", "number", False, "Target box size in px, to pick the best rendition."),
               ],
               response={"clips": [{"provider": "pexels", "id": "856789", "preview_url": "https://videos.pexels.com/…/small.mp4", "thumbnail_url": "https://images.pexels.com/…", "download_url": "https://videos.pexels.com/…/hd.mp4", "width": 1920, "height": 1080, "duration": 12.0, "fps": 25.0, "author": "Jane Doe", "page_url": "https://www.pexels.com/video/856789/", "tags": "office, laptop", "description": "Person typing"}]}),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/stock-footage", "Set a scene's stock clip",
               "Uses a clip from the search results. Uses AI-edit credits.",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("provider", "string", True, "`pexels` or `pixabay`."),
                   ("clip_id", "string", True, "The clip's `id` from search."),
                   ("download_url", "string", True, "From search."),
                   ("width / height / duration", "number", False, "From search."),
                   ("author / page_url", "string", False, "Attribution, from search."),
               ],
               response={"asset_id": 9950, "filename": "pexels_856789.mp4", "video_url": "https://media.blog2video.app/…/pexels_856789.mp4", "audio_variant_url": None, "has_audio": False, "duration_seconds": 12.0, "width": 1920, "height": 1080, "source_author": "Jane Doe", "source_provider": "pexels"}),
            ep("GET", "/api/projects/{project_id}/stock-footage/pending", "List clips pending review",
               "For projects at `awaiting_stock_footage_review`.",
               params=[PROJECT_ID],
               response={"status": "awaiting_stock_footage_review", "awaiting": True, "scenes": [{"scene_id": 5012, "order": 1, "title": "Why remote teams stall", "scene_type": "content", "layout": "hero_image", "duration_seconds": 7.4, "image_focus_x": None, "image_focus_y": None, "image_zoom": None, "video_start_seconds": None, "clip": {"filename": "pexels_856789.mp4", "url": "https://media.blog2video.app/…/pexels_856789.mp4", "duration_seconds": 12.0, "author": "Jane Doe", "provider": "pexels"}}]}),
            ep("POST", "/api/projects/{project_id}/stock-footage/link", "Replace a reviewed clip",
               params=[PROJECT_ID],
               body=[("scene_id", "integer", True, "Scene to change."), ("filename", "string", True, "Filename of a `video` asset in this project.")],
               response={"detail": "Clip linked", "scene_id": 5012, "filename": "pexels_1234.mp4"}),
            ep("POST", "/api/projects/{project_id}/stock-footage/approve", "Approve stock clips",
               "Resumes a project at `awaiting_stock_footage_review`.",
               params=[PROJECT_ID], response={"detail": "Approved", "status": "generated"}),
            ep("POST", "/api/projects/{project_id}/stock-footage/reject", "Reject stock clips",
               "Discards the selected clips and uses images instead.",
               params=[PROJECT_ID], response={"detail": "Rejected — reverted to images", "status": "generated"}),
        ],
    },
    {
        "id": "voiceovers",
        "title": "Voiceovers, voice & language",
        "description": "Manage voices, voiceovers and translation.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/change-voice", "Change the voice",
               "Re-records all voiceovers. Runs in the background; poll `voice-change-status`.",
               params=[PROJECT_ID],
               body=[
                   ("voice_gender", "string", False, "`female` or `male`."),
                   ("voice_accent", "string", False, "`american` or `british`."),
                   ("custom_voice_id", "string", False, "A saved voice id; overrides gender/accent."),
                   ("voice_emotion", "string", False, "Narration tone preset (paid plans)."),
               ],
               request={"custom_voice_id": "21m00Tcm4TlvDq8ikWAM"},
               response={"started": True, "total": 8}),
            ep("GET", "/api/projects/{project_id}/voice-change-status", "Get voice change status",
               "Also reports `delete-voiceover` progress.",
               params=[PROJECT_ID], response=VOICE_JOB_STATUS),
            ep("POST", "/api/projects/{project_id}/delete-voiceover", "Delete all voiceovers",
               "Removes narration from every scene. Runs in the background; poll `voice-change-status`.",
               params=[PROJECT_ID], response={"started": True, "total": 8}),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/voiceover", "Upload a scene voiceover",
               "Replaces one scene's narration (MP3, WAV or M4A). The scene duration follows the audio.",
               params=[PROJECT_ID, SCENE_ID], content_type=MULTIPART,
               body=[("audio", "file", True, "The recording.")],
               response={**SCENE, "duration_seconds": 9.1}),
            ep("POST", "/api/projects/{project_id}/change-language", "Translate a project",
               "Translates all text and re-records voiceovers. Runs in the background; poll `language-change-status`.",
               params=[PROJECT_ID],
               body=[("content_language", "string", True, "ISO code (`es`) or name (`Spanish`).")],
               request={"content_language": "es"},
               response={"started": True, "total": 16, "content_language": "es"}),
            ep("GET", "/api/projects/{project_id}/language-change-status", "Get translation status",
               params=[PROJECT_ID],
               response={"active": True, "done": False, "error": None, "total": 16, "completed": 9, "progress": 56, "phase": "voiceovers", "status": "language_regenerating", "r2_video_url": None, "kind": "language_change", "content_language": "es"}),
            ep("POST", "/api/voice/preview", "Preview a voice",
               "Returns an MP3 sample.",
               body=[
                   ("voice_gender / voice_accent", "string", False, "Built-in voice selection."),
                   ("custom_voice_id", "string", False, "A saved voice id."),
                   ("voice_emotion", "string", False, "Tone preset."),
                   ("video_style", "string", False, "Style used to pick the sample line."),
               ],
               request={"voice_gender": "male", "voice_accent": "british"},
               response=None, response_note="Binary MP3 (`audio/mpeg`)."),
            ep("GET", "/api/projects/{project_id}/voices", "List voices for a project",
               params=[PROJECT_ID], response=[SAVED_VOICE]),
            ep("GET", "/api/voices/saved", "List saved voices",
               "Voices usable as `custom_voice_id`. Built-in voices: `GET /api/voices` (no authentication).",
               response=[SAVED_VOICE]),
            ep("POST", "/api/voices/saved", "Save a voice",
               body=[
                   ("voice_id", "string", True, "ElevenLabs voice id."),
                   ("name", "string", True, "Display name."),
                   ("source", "string", False, "`prebuilt` or `custom`."),
                   ("preview_url / gender / accent / description / plan", "string", False, "Optional metadata."),
                   ("custom_voice_id", "integer", False, "Custom voice to link."),
               ],
               request={"voice_id": "21m00Tcm4TlvDq8ikWAM", "name": "Rachel", "source": "prebuilt"},
               response=SAVED_VOICE),
            ep("DELETE", "/api/voices/saved/{voice_id}", "Remove a saved voice",
               params=[("voice_id", "path", "string", True, "The saved voice's `voice_id`.")],
               response={"ok": True}),
            ep("POST", "/api/voices/design-from-prompt", "Design a voice from a prompt",
               "Returns voice previews. Register the chosen one with `POST /api/voices/custom`. Limited to 40 designs per day.",
               body=[("prompt", "string", True, "Voice description, 20–1000 characters.")],
               request={"prompt": "A warm, confident female narrator in her thirties with a light British accent"},
               response={"previews": [{"generated_voice_id": "gvx_8Hq2…", "audio_base_64": "…", "media_type": "audio/mpeg", "duration_secs": 6.1}], "text": "…"},
               errors=["429: daily voice design limit reached."]),
            ep("POST", "/api/voices/design-from-preset", "Design a voice from options",
               "Returns voice previews. Register the chosen one with `POST /api/voices/custom`. Limited to 40 designs per day.",
               body=[("gender / age / persona / speed / accent", "string", False, "Voice attributes.")],
               request={"gender": "male", "age": "middle-aged", "persona": "documentary narrator", "speed": "calm", "accent": "United States"},
               response={"previews": [{"generated_voice_id": "gvx_3Lp9…", "audio_base_64": "…", "media_type": "audio/mpeg", "duration_secs": 5.4}], "text": "…"},
               errors=["429: daily voice design limit reached."]),
            ep("GET", "/api/voices/custom", "List custom voices", response=[CUSTOM_VOICE]),
            ep("POST", "/api/voices/custom", "Register a designed voice",
               "Stores a voice created with the voice design endpoints.",
               body=[
                   ("voice_id", "string", True, "The generated voice id."),
                   ("source", "string", True, "`prompt` or `preset`."),
                   ("name / prompt_text / preview_url", "string", False, "Optional metadata."),
               ],
               response=CUSTOM_VOICE),
            ep("POST", "/api/voices/clone", "Clone a voice from a recording",
               "Requires 30 seconds to several minutes of clean speech. Paid plans only.",
               content_type=MULTIPART,
               body=[
                   ("name", "string", True, "Voice name."),
                   ("file", "file", True, "The recording."),
                   ("remove_background_noise", "string", False, "`true` (default) or `false`."),
               ],
               response=CUSTOM_VOICE),
            ep("GET", "/api/voices/custom/{custom_voice_id}/preview", "Get a custom voice preview",
               params=[("custom_voice_id", "path", "integer", True, "The custom voice's id.")],
               response={"preview_url": "https://…/preview.mp3", "ready": True}),
            ep("DELETE", "/api/voices/custom/{custom_voice_id}", "Delete a custom voice",
               params=[("custom_voice_id", "path", "integer", True, "The custom voice's id.")],
               response={"ok": True}),
        ],
    },
    {
        "id": "templates",
        "title": "Templates, styles & music",
        "description": "Select templates, video styles and background music.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/change-template-regenerate-layouts", "Switch template",
               "Moves the project to another template and rebuilds all layouts. Uses one video. Runs in the background.",
               params=[PROJECT_ID],
               body=[("template", "string", True, "Built-in, custom or crafted template id.")],
               request={"template": "nightfall"},
               response={"id": 55, "project_id": 812, "user_id": 41, "target_template": "nightfall", "status": "queued", "total_scenes": 8, "processed_scenes": 0, "error_message": None}),
            ep("GET", "/api/projects/{project_id}/template-change-status", "Get template switch status",
               params=[PROJECT_ID],
               response={"id": 55, "project_id": 812, "target_template": "nightfall", "status": "running", "total_scenes": 8, "processed_scenes": 5, "error_message": None},
               response_note="`status`: `queued`, `running`, `completed`, `failed`. `null` when no job has run."),
            ep("GET", "/api/custom-templates", "List custom templates",
               "Apply one with `template: \"custom_<id>\"`. Built-in templates: `GET /api/templates` (no authentication).",
               response=[CUSTOM_TEMPLATE]),
            ep("GET", "/api/custom-templates/{template_id}", "Get a custom template",
               params=[CUSTOM_TEMPLATE_ID],
               response=CUSTOM_TEMPLATE),
            ep("GET", "/api/crafted-templates", "List crafted templates",
               "Designer templates available to the account.",
               response=[{"id": "crafted_orbit", "name": "Orbit", "description": "Bold geometric", "genres": ["tech"], "preview_colors": {"accent": "#22D3EE", "bg": "#0F172A", "text": "#F8FAFC"}}]),
            ep("GET", "/api/crafted-templates/{template_id}", "Get a crafted template",
               params=[("template_id", "path", "string", True, "Crafted template id.")],
               response={"id": "crafted_orbit", "name": "Orbit", "description": "Bold geometric", "genres": ["tech"], "preview_colors": {"accent": "#22D3EE"}, "hero_layout": "hero", "fallback_layout": "bullets", "valid_layouts": ["hero", "bullets", "stat"]}),
            ep("GET", "/api/projects/{project_id}/custom-templates", "List custom templates for a project",
               params=[PROJECT_ID], response=[CUSTOM_TEMPLATE]),
            ep("GET", "/api/projects/{project_id}/custom-templates/{template_id}/code", "Get custom template code for a project",
               params=[PROJECT_ID, ("template_id", "path", "string", True, "Custom template id.")],
               response={"intro_code": "…", "outro_code": "…", "content_codes": ["…"]}),
            ep("GET", "/api/projects/{project_id}/crafted-templates", "List crafted templates for a project",
               params=[PROJECT_ID], response=[{"id": "crafted_orbit", "name": "Orbit"}]),
            ep("GET", "/api/projects/{project_id}/crafted-templates/{template_id}", "Get a crafted template for a project",
               params=[PROJECT_ID, ("template_id", "path", "string", True, "Crafted template id.")],
               response={"id": "crafted_orbit", "name": "Orbit", "valid_layouts": ["hero", "bullets"]}),
            ep("GET", "/api/video-styles", "List video styles",
               "Styles usable as `video_style`, with the current selection.",
               response={"styles": [{"id": "explainer", "name": "Explainer", "description": "Teach one idea clearly", "kind": "builtin"}], "selected_ids": ["explainer", "storytelling"], "auto_style": {"id": "auto", "name": "Auto", "description": "Pick the best style for the content"}, "max_selected": 4, "min_selected": 1}),
            ep("PUT", "/api/video-styles/selection", "Set selected styles",
               body=[("style_ids", "string[]", True, "Style ids to show in pickers.")],
               request={"style_ids": ["explainer", "promotional"]},
               response={"selected_ids": ["explainer", "promotional"], "max_selected": 4, "min_selected": 1}),
            ep("GET", "/api/background-music/tracks", "List background music",
               "Use `track_id` as `bgm_track_id`.",
               response=[{"track_id": "corporate_upbeat", "display_name": "Corporate Upbeat", "mood": "Motivational", "r2_url": "https://media.blog2video.app/bgm/corporate_upbeat.mp3"}]),
            ep("GET", "/api/stock-data", "Get stock price data",
               params=[("ticker", "query", "string", False, "e.g. `AAPL`."), ("days", "query", "integer", False, "History length in days.")],
               response={"ticker": "AAPL", "period": "30d", "info": {"name": "Apple Inc.", "sector": "Technology", "industry": "Consumer Electronics", "currency": "USD", "current_price": 227.1, "previous_close": 225.4, "market_cap": 3.4e12, "pe_ratio": 34.2, "dividend_yield": 0.004}, "prices": [{"date": "2026-09-01", "open": 218.0, "high": 220.1, "low": 217.4, "close": 219.3, "volume": 51230000}], "income_statement": [], "balance_sheet": []}),
        ],
    },
    {
        "id": "custom-templates",
        "title": "Custom templates",
        "description": "Create and edit custom templates. Creation uses a template slot; AI edits use AI-edit credits.",
        "endpoints": [
            ep("POST", "/api/custom-templates/extract-theme", "Extract a theme from a website",
               "Returns colors, fonts, logos and a screenshot for `POST /api/custom-templates`.",
               body=[("url", "string", True, "Website to read.")],
               request={"url": "https://acme.com"},
               response={"extractable": True, "reason": "", "theme": CUSTOM_TEMPLATE["theme"], "template_name": "Acme", "logo_urls": ["https://acme.com/logo.svg"], "og_image": "https://acme.com/og.png", "screenshot_url": "https://media.blog2video.app/…/acme.png"},
               errors=["Returns `extractable: false` with a `reason` if the site cannot be read."]),
            ep("POST", "/api/custom-templates/extract-theme-from-doc", "Extract a theme from a brand document",
               "Accepts PDF, DOCX, MD or TXT.",
               content_type=MULTIPART,
               body=[("file", "file", True, "The document."), ("name", "string", True, "Template name.")],
               response={"extractable": True, "reason": "", "theme": CUSTOM_TEMPLATE["theme"], "template_name": "Acme", "logo_urls": [], "og_image": "", "screenshot_url": ""}),
            ep("POST", "/api/custom-templates/extract-theme-from-prompt", "Extract a theme from a prompt",
               body=[("prompt", "string", True, "Description of the desired look."), ("name", "string", False, "Template name.")],
               request={"prompt": "Dark, minimal, neon orange accents, bold sans-serif headings", "name": "Neon"},
               response={"extractable": True, "reason": "", "theme": CUSTOM_TEMPLATE["theme"], "template_name": "Neon", "logo_urls": [], "og_image": "", "screenshot_url": ""}),
            ep("POST", "/api/custom-templates", "Create a custom template",
               "Uses one custom-template slot. Generate the scenes next with `generate-code`.",
               body=[
                   ("name", "string", True, "Template name."),
                   ("theme", "object", True, "Theme from an extract endpoint, optionally edited."),
                   ("source_url", "string", False, "Where the theme came from."),
                   ("logo_urls", "string[]", False, "Logo candidates from the extract call."),
                   ("og_image / screenshot_url", "string", False, "Reference images from the extract call."),
               ],
               request={"name": "Acme brand", "source_url": "https://acme.com", "theme": CUSTOM_TEMPLATE["theme"], "logo_urls": ["https://acme.com/logo.svg"]},
               response=CUSTOM_TEMPLATE,
               errors=["403 `custom_template_limit`: no template slots remaining."]),
            ep("PUT", "/api/custom-templates/{template_id}", "Update a custom template",
               params=[CUSTOM_TEMPLATE_ID],
               body=[("name", "string", False, "New name."), ("theme", "object", False, "New theme.")],
               request={"name": "Acme 2026"}, response=CUSTOM_TEMPLATE),
            ep("DELETE", "/api/custom-templates/{template_id}", "Delete a custom template",
               params=[CUSTOM_TEMPLATE_ID, ("force", "query", "boolean", False, "Delete even if projects use it.")],
               response={"detail": "Custom template deleted"}),
            ep("POST", "/api/custom-templates/{template_id}/generate-code", "Generate template scenes",
               "Runs in the background; poll `generation-status`.",
               params=[CUSTOM_TEMPLATE_ID], status=202,
               response={"detail": "Code generation started", "template_id": 58}),
            ep("GET", "/api/custom-templates/{template_id}/generation-status", "Get generation status",
               "Poll until `status` is `complete` or `error`.",
               params=[CUSTOM_TEMPLATE_ID],
               response={"status": "generating", "step": "content", "running": True, "error": None, "stage": "content", "run_id": 311, "scenes_done": 3, "scenes_total": 7, "scenes_total_final": True}),
            ep("POST", "/api/custom-templates/{template_id}/regenerate-code", "Regenerate template scenes",
               "Uses one custom-template slot. Poll `generation-status`.",
               params=[CUSTOM_TEMPLATE_ID], status=202,
               response={"detail": "Regeneration started", "template_id": 58}),
            ep("POST", "/api/custom-templates/{template_id}/resume-generation", "Resume generation",
               "Continues a stalled run and keeps completed scenes.",
               params=[CUSTOM_TEMPLATE_ID], status=202,
               response={"detail": "Generation resumed", "template_id": 58, "run_id": 312}),
            ep("GET", "/api/custom-templates/{template_id}/code", "Get template code",
               params=[CUSTOM_TEMPLATE_ID],
               response={"component_code": None, "intro_code": "…", "outro_code": "…", "content_codes": ["…"], "layout_prop_schemas": None, "design_version": 2, "image_modes": {"content_0": "background"}}),
            ep("POST", "/api/custom-templates/{template_id}/upload-logo", "Upload a logo",
               params=[CUSTOM_TEMPLATE_ID], content_type=MULTIPART,
               body=[("file", "file", True, "PNG, JPG, SVG or WebP.")],
               response={"logo_url": "https://media.blog2video.app/…/logo.png", "template": CUSTOM_TEMPLATE}),
            ep("POST", "/api/custom-templates/{template_id}/scenes/{scene_key}/ai-edit", "Edit a scene with AI",
               "Saves the result as a draft. Uses AI-edit credits; poll `ai-edit/status`.",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "`intro`, `outro` or `content_<n>` (from 0).")],
               body=[
                   ("prompt", "string", True, "What to change."),
                   ("keep_geometry", "boolean", False, "Keep the layout, change styling only."),
                   ("from_blueprint", "boolean", False, "Rebuild the scene from its original plan."),
               ],
               request={"prompt": "Make the headline larger and add a subtle grid background"},
               status=202, response={"edit_id": "58:content_1:1727690000", "template_id": 58, "scene_key": "content_1"}),
            ep("GET", "/api/custom-templates/{template_id}/scenes/{scene_key}/ai-edit/status", "Get scene edit status",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key."), ("edit_id", "query", "string", False, "From the edit call.")],
               response={"status": "complete", "step": "done", "running": False, "error": None, "draft_version_id": 902, "edit_id": "58:content_1:1727690000"}),
            ep("GET", "/api/custom-templates/{template_id}/scene-drafts", "List pending drafts",
               params=[CUSTOM_TEMPLATE_ID],
               response={"drafts": ["content_1"], "running": []}),
            ep("GET", "/api/custom-templates/{template_id}/scenes/{scene_key}/draft", "Get a scene draft",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key.")],
               response={"version_id": 902, "scene_key": "content_1", "label": "AI edit", "code": "…", "aspect_ratio": "landscape"}),
            ep("POST", "/api/custom-templates/{template_id}/scenes/{scene_key}/draft/apply", "Apply a scene draft",
               "Saves a restorable version before applying.",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key.")],
               response=CUSTOM_TEMPLATE),
            ep("POST", "/api/custom-templates/{template_id}/scenes/{scene_key}/draft/discard", "Discard a scene draft",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key.")],
               response={"detail": "Draft discarded"}),
            ep("PATCH", "/api/custom-templates/{template_id}/scenes/{scene_key}/chart", "Set chart sample data",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key.")],
               body=[("chartType", "string", False, "e.g. `bar`, `line`, `pie`."), ("chartTable", "object", False, "Sample data table.")],
               request={"chartType": "bar", "chartTable": {"columns": ["Year", "Revenue"], "rows": [["2024", 12], ["2025", 19]]}},
               response=CUSTOM_TEMPLATE),
            ep("PATCH", "/api/custom-templates/{template_id}/scenes/{scene_key}/font-defaults", "Set scene text sizes",
               params=[CUSTOM_TEMPLATE_ID, ("scene_key", "path", "string", True, "Scene key.")],
               body=[("title / description", "object", False, "Sizes per orientation; omitted keys stay as they are.")],
               request={"title": {"landscape": 72, "portrait": 56}},
               response=CUSTOM_TEMPLATE),
            ep("PATCH", "/api/custom-templates/{template_id}/scenes/font-defaults", "Set text sizes for multiple scenes",
               params=[CUSTOM_TEMPLATE_ID],
               body=[("scenes", "object", True, "Scene key → `{title?, description?}`.")],
               request={"scenes": {"intro": {"title": {"landscape": 88}}, "content_0": {"description": {"landscape": 34}}}},
               response=CUSTOM_TEMPLATE),
            ep("GET", "/api/custom-templates/{template_id}/versions", "List versions",
               params=[CUSTOM_TEMPLATE_ID],
               response={"current_version_id": 904, "versions": [{"id": 904, "label": "Applied AI edit", "created_at": "2026-09-30T11:02:10"}]}),
            ep("POST", "/api/custom-templates/{template_id}/versions/{version_id}/rollback", "Restore a version",
               params=[CUSTOM_TEMPLATE_ID, ("version_id", "path", "integer", True, "From `versions`.")],
               response=CUSTOM_TEMPLATE),
            ep("POST", "/api/custom-templates/{template_id}/rating", "Rate a template",
               params=[CUSTOM_TEMPLATE_ID],
               body=[("rating", "integer", True, "1 to 5."), ("suggestion", "string", False, "What would make it better.")],
               request={"rating": 5},
               response={"id": 7, "user_id": 41, "custom_template_id": 58, "rating": 5, "suggestion": None, "created_at": "2026-09-30T11:05:00", "updated_at": "2026-09-30T11:05:00"}),
        ],
    },
    {
        "id": "video-styles",
        "title": "Video styles",
        "description": "Manage the writing styles applied to scripts. Pass a style `id` as `video_style`.",
        "endpoints": [
            ep("POST", "/api/video-styles/ai-draft", "Draft a style with AI",
               "Returns a name and guidance for `POST /api/video-styles/custom`.",
               body=[("prompt", "string", True, "Describe the style.")],
               request={"prompt": "Punchy, witty, short sentences for developer audiences"},
               response={"name": "Dev Punchy", "guidance": "Open with a bold claim. Keep sentences under 12 words…"}),
            ep("POST", "/api/video-styles/custom", "Create a custom style",
               body=[
                   ("name", "string", True, "Style name."),
                   ("guidance", "string", True, "Instructions for the scriptwriter."),
                   ("creation_method", "string", False, "`manual` or `ai`."),
                   ("source_prompt", "string", False, "The prompt used for an AI draft."),
               ],
               request={"name": "Dev Punchy", "guidance": "Open with a bold claim…", "creation_method": "ai", "source_prompt": "Punchy, witty…"},
               response={"id": "custom:12", "custom_id": 12, "name": "Dev Punchy", "description": "Open with a bold claim…", "guidance": "Open with a bold claim…", "kind": "custom", "editable": True, "creation_method": "ai", "source_prompt": "Punchy, witty…", "version": 1, "created_at": "2026-09-30T10:00:00", "updated_at": "2026-09-30T10:00:00", "pinned": False, "selected_ids": ["explainer", "custom:12"]}),
            ep("PATCH", "/api/video-styles/custom/{style_id}", "Edit a custom style",
               params=[("style_id", "path", "integer", True, "The style's `custom_id`.")],
               body=[("name", "string", True, "Style name."), ("guidance", "string", True, "Instructions."), ("version", "integer", False, "Version being edited; used to detect conflicts.")],
               request={"name": "Dev Punchy", "guidance": "Open with a question…", "version": 1},
               response={"id": "custom:12", "custom_id": 12, "name": "Dev Punchy", "guidance": "Open with a question…", "kind": "custom", "version": 2}),
            ep("DELETE", "/api/video-styles/custom/{style_id}", "Delete a custom style",
               params=[("style_id", "path", "integer", True, "The style's `custom_id`.")],
               response={"ok": True, "selected_ids": ["explainer"]}),
            ep("PATCH", "/api/video-styles/builtin/{style_key}", "Customize a built-in style",
               params=[("style_key", "path", "string", True, "`explainer`, `promotional` or `storytelling`.")],
               body=[("guidance", "string", True, "Replacement guidance."), ("version", "integer", True, "Current version.")],
               request={"guidance": "Explain with one analogy per scene…", "version": 0},
               response={"id": "explainer", "name": "Explainer", "description": "Teach one idea clearly", "guidance": "Explain with one analogy per scene…", "kind": "builtin", "editable": True, "available": True, "customized": True, "version": 1, "default_guidance": "…", "updated_at": "2026-09-30T10:00:00", "pinned": False}),
            ep("DELETE", "/api/video-styles/builtin/{style_key}", "Reset a built-in style",
               params=[("style_key", "path", "string", True, "Built-in style key.")],
               response={"id": "explainer", "name": "Explainer", "kind": "builtin", "customized": False, "guidance": "…", "version": 0}),
            ep("PUT", "/api/video-styles/pin", "Set the learning target",
               "Script edits are learned into the pinned style.",
               body=[("target_ref", "string", True, "`your_style`, a built-in key, or `custom:<id>`.")],
               request={"target_ref": "custom:12"},
               response={"pinned_target": "custom:12"}),
            ep("PATCH", "/api/video-styles/your-style", "Edit Your Style",
               body=[("guidance", "string", True, "The learned guidance, edited."), ("version", "integer", True, "Current version.")],
               request={"guidance": "Prefers short intros and concrete numbers…", "version": 3},
               response={"guidance": "Prefers short intros and concrete numbers…", "version": 4, "updated_at": "2026-09-30T10:00:00"},
               errors=["409: modified since last read; fetch and retry."]),
            ep("DELETE", "/api/video-styles/your-style", "Clear Your Style",
               "Erases the learned profile.",
               response={"ok": True, "selected_ids": ["explainer"]}),
            ep("DELETE", "/api/auth/me/script-preferences", "Clear Your Style (legacy)",
               "Equivalent to `DELETE /api/video-styles/your-style`.",
               response_note="Returns the account, as `GET /api/auth/me`."),
        ],
    },
    {
        "id": "ai-editing",
        "title": "AI editing",
        "description": "Edit generated videos with natural-language instructions. Uses AI-edit credits.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/chat", "Edit a video by instruction",
               "Applies the instruction to the affected scenes and summarizes the changes.",
               params=[PROJECT_ID],
               body=[("message", "string", True, "What to change.")],
               request={"message": "Make scene 3 shorter and end with a question"},
               response={"reply": "Done. I tightened scene 3 and ended it with a question.", "changes_made": "Updated scene 3 narration and display text.", "updated_scenes": [SCENE]}),
            ep("GET", "/api/projects/{project_id}/chat/history", "Get chat history",
               params=[PROJECT_ID],
               response=[{"role": "user", "content": "Make scene 3 shorter"}, {"role": "assistant", "content": "Done. I tightened scene 3…"}]),
            ep("POST", "/api/projects/{project_id}/script-review/scenes/{scene_id}/ai-preview", "Preview an AI scene rewrite",
               "Available at `awaiting_script_review`. Returns a preview only; nothing is saved.",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("title / display_text / narration_text", "string", True, "The scene as it stands."),
                   ("draft_scenes", "object[]", True, "All scenes as currently drafted: `{id, title, display_text, narration_text}`."),
                   ("revision", "integer", True, "Review revision being edited."),
                   ("instruction", "string", True, "What to change."),
               ],
               request={"title": "Why remote teams stall", "display_text": "Handoffs", "narration_text": "Most remote teams…", "draft_scenes": [{"id": 5012, "title": "Why remote teams stall", "display_text": "Handoffs", "narration_text": "Most remote teams…"}], "revision": 3, "instruction": "More upbeat"},
               response={"revision": 3, "title": "Why remote teams win", "display_text": "Handoffs, fixed", "narration_text": "Great remote teams…", "source_fingerprint": "a1b2c3"}),
        ],
    },
    {
        "id": "downloads",
        "title": "Downloads",
        "description": "Download project source files and free templates.",
        "endpoints": [
            ep("GET", "/api/projects/{project_id}/download-studio", "Download the Remotion project",
               "Editable Remotion source as a zip. Requires a paid plan or a Studio purchase.",
               params=[PROJECT_ID],
               response_note="A `.zip` file (`application/zip`)."),
            ep("GET", "/api/templates/free-download/{slug}", "Download a free template",
               params=[("slug", "path", "string", True, "Template slug from the free templates gallery.")],
               response_note="A `.zip` file (`application/zip`)."),
            ep("GET", "/api/templates/free-download-all", "Download all free templates",
               response_note="A `.zip` file (`application/zip`)."),
        ],
    },
    {
        "id": "avatars",
        "title": "Avatars",
        "description": "Add presenter avatars to scenes. Each scene uses 10 AI-edit credits.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/avatar-batch/authorize", "Generate avatars for multiple scenes",
               "Charges credits for 5–10 scenes (or all remaining) and queues them.",
               params=[PROJECT_ID],
               body=[
                   ("scene_ids", "integer[]", True, "Scenes to add the presenter to."),
                   ("avatar_preset", "string", False, "Presenter id."),
                   ("avatar_motion_style", "string", False, "`subtle`, `natural` or `expressive`."),
               ],
               request={"scene_ids": [5012, 5013, 5014, 5015, 5016], "avatar_preset": "maya"},
               response={"authorized": True, "scene_ids": [5012, 5013, 5014, 5015, 5016], "job_ids": [301, 302, 303, 304, 305], "credits_charged": 50, "credits_remaining": 4820}),
            ep("GET", "/api/projects/{project_id}/avatar-progress", "Get avatar batch progress",
               params=[PROJECT_ID],
               response={"scenes": [{"scene_id": 5012, "status": "completed"}], "counts": {"completed": 3, "running": 1, "queued": 1, "failed": 0}, "total": 5, "batch_status": "running", "eligible_total": 8}),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/avatar", "Generate a scene avatar",
               params=[PROJECT_ID, SCENE_ID], content_type=FORM,
               body=[("avatar_preset", "string", False, "Presenter id.")],
               response={"started": True, "queued": True, "job_id": 306, "avatar_preset": "maya", "queue_position": 2}),
            ep("GET", "/api/projects/{project_id}/scenes/{scene_id}/avatar-status", "Get scene avatar status",
               params=[PROJECT_ID, SCENE_ID],
               response={"active": False, "done": True, "error": None, "status": "completed", "phase": None, "kind": "avatar", "has_avatar": True, "has_matte": False, "duration_seconds": 7.4}),
            ep("DELETE", "/api/projects/{project_id}/scenes/{scene_id}/avatar", "Remove a scene's avatar",
               params=[PROJECT_ID, SCENE_ID], response=SCENE),
            ep("POST", "/api/projects/{project_id}/scenes/{scene_id}/avatar-matte", "Remove an avatar background",
               "Required before placing the avatar on a custom background.",
               params=[PROJECT_ID, SCENE_ID], response={"started": True, "queued": True, "job_id": 410}),
            ep("POST", "/api/projects/{project_id}/avatar-matte-all", "Remove all avatar backgrounds",
               params=[PROJECT_ID], response={"started": 5, "queued": True, "job_ids": [410, 411, 412, 413, 414]}),
            ep("POST", "/api/projects/{project_id}/avatar-retry-failed", "Retry failed avatars",
               params=[PROJECT_ID], response={"retried": 1, "jobs": [{"scene_id": 5014, "job_id": 320}], "skipped_exhausted": [], "blocked_refunded": []}),
            ep("PATCH", "/api/projects/{project_id}/scenes/{scene_id}/avatar-appearance", "Set scene avatar appearance",
               "Per-scene overrides; `null` restores the project setting.",
               params=[PROJECT_ID, SCENE_ID],
               body=[
                   ("avatar_shape", "string", False, "`circle`, `rounded` or `square`."),
                   ("avatar_size", "number", False, "Fraction of the video width."),
                   ("avatar_position", "string", False, "Corner or edge placement, e.g. `bottom_left`."),
                   ("avatar_bg", "string", False, "`transparent` or a hex color."),
                   ("avatar_opacity / avatar_shadow", "number", False, "0 to 1."),
               ],
               response=SCENE),
            ep("PATCH", "/api/projects/{project_id}/scenes/{scene_id}/avatar-focus", "Set scene avatar framing",
               params=[PROJECT_ID, SCENE_ID],
               body=[("avatar_focus_x / avatar_focus_y", "number", False, "Focal point in percent."), ("avatar_zoom", "number", False, "0.5 to 4.")],
               response=SCENE),
            ep("POST", "/api/projects/{project_id}/avatar-portrait", "Upload a presenter photo",
               params=[PROJECT_ID], content_type=MULTIPART, body=[("file", "file", True, "A clear, front-facing portrait.")],
               response={"ok": True, "avatar_custom_image_url": "https://…/portrait.png", "has_custom_portrait": True}),
            ep("DELETE", "/api/projects/{project_id}/avatar-portrait", "Remove the presenter photo",
               params=[PROJECT_ID], response={"ok": True, "has_custom_portrait": False}),
        ],
    },
    {
        "id": "render",
        "title": "Render, download & preview",
        "description": "Render MP4 files and create live preview links.",
        "endpoints": [
            ep("POST", "/api/projects/{project_id}/render", "Render the video",
               "Starts an MP4 render. Does not use additional videos.",
               params=[
                   PROJECT_ID,
                   ("resolution", "query", "string", False, "`1080p` (default) or `720p`. Some templates always render at 720p."),
                   ("force_render", "query", "boolean", False, "`true` to re-render a video that was already rendered."),
               ],
               response={"detail": "Render started", "progress": 0, "resolution": "1080p", "render_run_id": "r_8f2c"},
               response_note="May return `Already rendered` (with `r2_video_url`) or `Render already running`."),
            ep("GET", "/api/projects/{project_id}/render-status", "Get render status",
               "Poll until `done` is true; `error` is set on failure.",
               params=[PROJECT_ID],
               response={"progress": 64, "rendered_frames": 3840, "total_frames": 6000, "done": False, "error": None, "time_remaining": "1m 10s", "eta_seconds": 70, "progress_unknown": False, "r2_video_url": None}),
            ep("POST", "/api/projects/{project_id}/cancel-render", "Cancel a render",
               params=[PROJECT_ID], response={"detail": "Render cancelled", "cancelled": True}),
            ep("GET", "/api/projects/{project_id}/download-url", "Get the MP4 link",
               params=[PROJECT_ID], response={"url": "https://media.blog2video.app/users/41/projects/812/video.mp4"}),
            ep("GET", "/api/projects/{project_id}/download", "Download the MP4",
               "Streams the file or redirects to it.",
               params=[PROJECT_ID], response=None, response_note="Binary `video/mp4`."),
            ep("GET", "/api/projects/{project_id}/render-still", "Render a frame",
               params=[PROJECT_ID, ("frame", "query", "integer", True, "Frame number (30 frames per second).")],
               response=None, response_note="Binary `image/png`."),
            ep("POST", "/api/projects/{project_id}/render-stills", "Render multiple frames",
               "Streams NDJSON, one line per frame with a base64 PNG.",
               params=[PROJECT_ID],
               body=[("frames", "integer[]", True, "Frame numbers.")],
               request={"frames": [0, 210, 420]},
               response=None, response_note="`application/x-ndjson`: `{\"index\": 0, \"total\": 3, \"image\": \"data:image/png;base64,…\"}`, or `{\"error\": \"…\"}` for a failed frame."),
            ep("POST", "/api/embed/token/{project_id}", "Create a live preview link",
               "A public player link that updates when the project changes. Embed it in an iframe.",
               params=[PROJECT_ID],
               response={"embed_token": "3f9a…c21", "preview_url": "https://blog2video.app/embed/3f9a…c21"}),
        ],
    },
    {
        "id": "v1",
        "title": "Simplified API (/api/v1)",
        "description": "Manage videos after creating them (see Quick start).",
        "endpoints": [
            ep("GET", "/api/v1/me", "Get account usage",
               response={"type": "api_key", "email": "you@company.com", "plan": "pro", "videos_used": 12, "video_limit": 150, "video_credits": 50, "videos_remaining": 138, "can_create_video": True}),
            ep("GET", "/api/v1/catalog", "Get catalog",
               response={"templates": [{"id": "default", "name": "Default", "preview_url": "https://…/default.png"}], "voices": [{"voice_id": "21m00Tcm4TlvDq8ikWAM", "name": "Rachel", "preview_url": "https://…/rachel.mp3"}], "video_styles": {"styles": [{"id": "explainer", "name": "Explainer"}], "selected_ids": ["explainer"]}}),
            ep("GET", "/api/v1/videos", "List videos",
               params=[
                   ("external_user_id", "query", "string", False, "Only videos tagged with this id."),
                   ("limit", "query", "integer", False, "1 to 100. Default 20."),
                   ("before_id", "query", "integer", False, "Cursor from `next_before_id`."),
               ],
               response={"items": [{"video_id": 812, "name": "How remote teams ship faster", "status": "generated", "video_url": None, "external_user_id": "user-42", "metadata": None, "created_at": "2026-09-29T10:12:40"}], "next_before_id": None}),
            ep("PATCH", "/api/v1/videos/{video_id}", "Update video settings",
               "Accepts the `update-project` fields.",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"accent_color": "#0EA5E9"}, response=PROJECT),
            ep("PATCH", "/api/v1/videos/{video_id}/scenes/{scene_id}", "Edit a scene",
               "Accepts the scene edit fields.",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation."), SCENE_ID],
               request={"title": "New title"}, response=SCENE),
            ep("DELETE", "/api/v1/videos/{video_id}/scenes/{scene_id}", "Delete a scene",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation."), SCENE_ID], status=204, response=None,
               response_note="No content."),
            ep("POST", "/api/v1/videos/{video_id}/scenes/reorder", "Reorder scenes",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"scene_orders": [{"scene_id": 5013, "order": 1}]}, response=[SCENE]),
            ep("POST", "/api/v1/videos/{video_id}/scenes/{scene_id}/regenerate", "Regenerate a scene",
               "",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation."), SCENE_ID],
               body=[
                   ("description", "string", False, "What the scene should show or say."),
                   ("narration_text", "string", False, "New narration."),
                   ("regenerate_voiceover", "boolean", False, "Re-record the voiceover."),
                   ("layout", "string", False, "Force a layout."),
               ],
               response=SCENE),
            ep("POST", "/api/v1/videos/{video_id}/scenes", "Add a scene",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"prompt": "A closing tip", "position": 6}, status=202,
               response={"id": 31, "status": "queued", "current_step": "queued", "new_scene_id": None, "position": 6}),
            ep("GET", "/api/v1/videos/{video_id}/scenes/add-status", "Get add-scene status",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               response={"id": 31, "status": "completed", "new_scene_id": 5020}),
            ep("POST", "/api/v1/videos/{video_id}/template", "Switch template",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"template": "nightfall"}, status=202, response={"id": 55, "status": "queued", "target_template": "nightfall"}),
            ep("GET", "/api/v1/videos/{video_id}/template", "Get template switch status",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")], response={"id": 55, "status": "completed"}),
            ep("POST", "/api/v1/videos/{video_id}/voice", "Change the voice",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"voice_gender": "male"}, status=202, response={"started": True, "total": 8}),
            ep("GET", "/api/v1/videos/{video_id}/voice", "Get voice change status",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")], response=VOICE_JOB_STATUS),
            ep("POST", "/api/v1/videos/{video_id}/language", "Translate a video",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               request={"content_language": "es"}, status=202, response={"started": True, "total": 16, "content_language": "es"}),
            ep("GET", "/api/v1/videos/{video_id}/language", "Get translation status",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")],
               response={"active": False, "done": True, "progress": 100, "kind": "language_change", "content_language": "es"}),
            ep("POST", "/api/v1/videos/{video_id}/stock-footage/approve", "Approve stock clips",
               params=[("video_id", "path", "integer", True, "Video ID returned on creation.")], response={"detail": "Approved", "status": "generated"}),
        ],
    },
]

# Routes callable with an API key that need no auth at all (listed for completeness).
PUBLIC_NOTE = (
    "Built-in templates (`GET /api/templates`) and built-in voices (`GET /api/voices`, "
    "`GET /api/voices/prebuilt`, `GET /api/voices/previews`) need no authentication."
)


def catalog() -> dict:
    return {"version": 1, "guides": GUIDES, "sections": SECTIONS, "public_note": PUBLIC_NOTE}
