"""sync_prod_schema

Revision ID: bc6d48f1b3be
Revises: 57640a829335
Create Date: 2026-02-28 21:09:22.707857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6d48f1b3be'
down_revision: Union[str, None] = '57640a829335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('supported_video_style', sa.String(length=30), nullable=False),
    sa.Column('theme', sa.Text(), nullable=False),
    sa.Column('generated_prompt', sa.Text(), nullable=True),
    sa.Column('preview_image_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_templates_user_id'), 'custom_templates', ['user_id'], unique=False)
    # Add new columns WITH defaults so existing rows get a value
    op.add_column('projects', sa.Column('logo_size', sa.Float(), server_default='100.0', nullable=False))
    op.add_column('projects', sa.Column('video_style', sa.String(length=30), server_default="'explainer'", nullable=False))

    # Fill any NULLs in existing columns before making them NOT NULL
    op.execute("UPDATE projects SET template = 'default' WHERE template IS NULL")
    op.execute("UPDATE projects SET ai_assisted_editing_count = 0 WHERE ai_assisted_editing_count IS NULL")

    op.alter_column('projects', 'template',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('projects', 'ai_assisted_editing_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('scenes', sa.Column('display_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'display_text')
    op.alter_column('projects', 'ai_assisted_editing_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('projects', 'aspect_ratio',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'landscape'::character varying"),
               existing_nullable=False)
    op.alter_column('projects', 'template',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'default'::character varying"),
               nullable=True)
    op.alter_column('projects', 'logo_opacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.9'),
               existing_nullable=False)
    op.alter_column('projects', 'logo_position',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'bottom_right'::character varying"),
               existing_nullable=False)
    op.drop_column('projects', 'video_style')
    op.drop_column('projects', 'logo_size')
    op.drop_index(op.f('ix_custom_templates_user_id'), table_name='custom_templates')
    op.drop_table('custom_templates')
    # ### end Alembic commands ###
